spring:
  profiles:
    active: dev

  config:
    import: optional:application-secret.yml

# YouTube API configuration
youtube:
  api:
    key: ${youtube.api.key}
    application-name: ${youtube.api.application-name}
